title: "Dylan Zhou"
description: "Aspiring Data Engineer | Big Data & Real-time AI"
theme: minima
github:
  repository_url: https://github.com/MrMister1218/MrMister1218.github.io

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: home
      author_profile: false
      read_time: false
      comments: false
      share: false
      related: false
